name: Release Assets

on:
  release:
    types: [created]

jobs:
  build:
    name: Build and Upload Release Assets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [1.21.4]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build binary
      run: |
        env GOOS=${{ matrix.os }} GOARCH=amd64 go build -o noter-${{ matrix.os }}-amd64 .
      env:
        GO111MODULE: on

    - name: Upload binary to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./noter-${{ matrix.os }}-amd64
        asset_name: noter-${{ matrix.os }}-amd64
        asset_content_type: application/octet-stream
